mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.chinhae.librarymanagement.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/librarymanagement
    username: root
    password: 123456
    h2:
      console:
        enabled: true
    sql:
      init:
        mode: always


server:
  port: 8080